# enable auto-labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
   
labels:
  'bug':
    include:
      - '\bbug[s]?\b'
    exclude: []
  'help wanted':
    include:
      - '\bhelp( me)?\b'
    exclude:
      - '\b\[test(ing)?\]\b'
  'enhancement':
    include:
      - '\bfeat\b'
    exclude: []
   'ongoing work':
     include:
       - '\b(WIP|work in progress|ongoing work|work ongoing)\b'
     exclude: []
   'Blogs':
     include:
       - '\b*[Bb]logs*\b'
     exclude: []
    'EBooks':
      include:
        - '\b*[Ee][Bb]ooks*\b'
      exclude: []
